spring:
    #data:
    #  mongodb:
    #    authentication-database: admin
    #    username: root
    #    password: root
    #    database: test_db
    #    port: 27017
    #    host: localhost
    datasource:
      url: jdbc:mongodb://cluster0.jrims.mongodb.net/test
      username: aircast
      password: Ctu1a8RnoC2gx1fD
server:
  port: 8081


        #spring.jpa.hibernate.ddl-auto=update
        #spring.jpa.open-in-view=false
        #spring.datasource.data=mongo